### ISSUE TITLE
Install-Module Fails on mcr.microsoft.com/powershell:6.2.3-nanoserver-1803

### ISSUE THREAD

**Issue by bo67192** [aws/aws-tools-for-powershell#130]
I'm trying to run `Install-Module AWS.Tools.Installer -force -confirm:$false` inside of a container from `mcr.microsoft.com/powershell:6.2.3-nanoserver-1803`, but I get an error.

**Expected Behavior**

I expect to be able to run

`docker run -it mcr.microsoft.com/powershell:6.2.3-nanoserver-1803`

And then this inside of the container

`Install-Module AWS.Tools.Installer -force -confirm:$false;`

And have the AWS tools installer available

**Current Behavior**

Instead of getting the install I get this

```
PackageManagement\Install-Package : The module 'AWS.Tools.Installer' cannot be installed or updated because the authenticode signature of the file 'AWS.Tools.Installer.psd1' is not valid.
At C:\program files\powershell\Modules\PowerShellGet\PSModule.psm1:9508 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Steps to Reproduce (for bugs)**

Run

```
docker run -it mcr.microsoft.com/powershell:6.2.3-nanoserver-1803
```

to get a running powershell container, then run this inside of the container

```
Install-Module AWS.Tools.Installer -force -confirm:$false;
```

I'm not running any other commands inside of the container.

**Context**

We're trying to use the AWS Powershell tools modularized version 

**Your Environment**

I'm running windows 10 version 1803 build 17134.1246

```
PS > docker --version
Docker version 19.03.5, build 633a0ea
```

I appreciate any help

**Comment by matteo-prosperi** [comment]
Hello,
I will try to test this myself and see if I can get more insight.

This is very unexpected, you are getting an error running Install-Module 
Questions:
- are you able to install other AWS.Tools modules? e.g. `Install-Module AWS.Tools.EC2`
- are you able to install other non-AWS modules?
- what version of AWS.Tools.Installer are you installing? I suppose 1.0.1.0 (latest)
- could you give me your `$PSVersionTable` output?

Possible workarounds:
- If the issue is limited to AWS.Tools.Installer, you can simply skip installing it and instead directly `Install-Module` the AWS.Tools modules for the services you need. This would actually be my suggested process on a container. AWS.Tools.Installer provides a useful simplification of the update and uninstallation processes, especially in case you want to use multiple AWS.Tools modules. Considering that you should never update or uninstall stuff from a container, you most likely don't need AWS.Tools.Installer at all.
- If you are unable to install any of the AWS.Tools modules, you could instead download them all in zip format from https://sdk-for-net.amazonwebservices.com/ps/v4/latest/AWS.Tools.zip and simply unzip them in your module directory. This will also make the whole installation process much much faster if you plan to use a large number of modules. If you wish to use this method but prefer to lock the version of AWS.Tools that you are using, you can use a version-specific download link like https://sdk-for-net.amazonwebservices.com/ps/releases/AWS.Tools.4.0.4.0.zip.

**Comment by bo67192** [comment]
Hi @matteo-prosperi ,

Here's my `$psversiontable`

```
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0?}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

It looks like I can't install `AWS.Tools.EC2` either:

```
PS C:\> install-module AWS.Tools.EC2
WARNING: Win32Helpers: Cannot add type. Compilation errors occurred.
WARNING: Could not find a part of the path 'C:\Users\ContainerAdministrator\AppData\Local\Microsoft\Windows\PowerShell\PowerShellGet\PSRepositories.xml'.

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want
to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : The module 'AWS.Tools.Common' cannot be installed or updated because the authenticode signature of the file 'AWS.Tools.Common.psd1' is not valid.
At C:\program files\powershell\Modules\PowerShellGet\PSModule.psm1:9508 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

but it looks like I can't install Pester either

```
PS C:\> install-module Pester

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want
to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : The module 'Pester' cannot be installed or updated because the authenticode signature of the file 'Pester.psd1' is not valid.
At C:\program files\powershell\Modules\PowerShellGet\PSModule.psm1:9508 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShel\u2026lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : InvalidAuthenticodeSignature,ValidateAndGet-AuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

I'm confused by this error

`WARNING: Win32Helpers: Cannot add type. Compilation errors occurred.`

Does that mean there's something wrong with my container, and it's not an AWS module problem?

**Comment by matteo-prosperi** [comment]
Hi,
If you are not able to `Install-Module` anything, then it is likely an issue with your container.
I would suggest trying on a different container than `mcr.microsoft.com/powershell:6.2.3-nanoserver-1803` and see if you have better luck.

**Comment by hanischandrew** [comment]
Not that it's recommended, but you could add '-SkipPublisherCheck' to the Install-Module command.

**Comment by ashishdhingra** [comment]
Hi @bo67192,

Please confirm if this is no longer an issue or if you are able to test it on a different container as suggested by @matteo-prosperi.

Thanks,
Ashish
