### ISSUE TITLE
Cannot Import Module due to "Could not load file or assembly 'netstandard"

### ISSUE THREAD

**Issue by animusyosho** [aws/aws-tools-for-powershell#210]
I'm having a really difficult time importing Aws.Tools.Common on a fairly new windows server (2016 - up to date with windows updates). Installing the module goes fine, but importing it results in this error:
Import-Module : Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

It seems like this is a failure to load .net. I know you state 3.5 is required. I've tried installing .net 3.5, 2, 4 - The module still cannot import. Is there some programatic way I can ensure dependencies for this module are installed at the beginning of a script in order to avoid these issues with new servers going forward?

**Comment by ashishdhingra** [comment]
Hi @animusyosho,

Good morning.

Unfortunately, I'm unable to reproduce the issue on a fresh Windows Server 2016 EC2 instance. `AWS.Tools is the new modularized version of AWS Tools for PowerShell, compatible with PowerShell Core 6+ and Windows`.

Could you please provide information in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html 

Thanks,
Ashish
