### ISSUE TITLE
Cannot install AwsPowershell.NetCore module on any windows 10 machines

### ISSUE THREAD

**Issue by efie45** [aws/aws-tools-for-powershell#228]
## Description

I've tried to install the module on 4 different windows 10 machines and it will not install on any of them. I've used the -Force and -SkipPublisherCheck parameters for Install-Module and bypassed any execution policies. 

The module downloads as shown in the progress bar but then hangs and does nothing. I've let it run for over half an hour and get no feedback at all. I've tried from both Powershell terminal, windows terminal, and ISE as admin.

If I try to install directly by extracting the .zip file mentioned in the installation guide here:

https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-windows.html

I get the following error upon trying to import the module:

Import-Module : Could not load file or assembly
'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AwsPowershell.NetCore\4.1.14.0\AWSSDK.AccessAnalyzer.dll'
or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module AwsPowershell.NetCore
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
    
## Environment

The windows boxes vary in version from 1909 to 20H2. 3 boxes I've tried are Hyper-V machines and 1 is a Parallels Windows box. 

I've never had an issue on any of these boxes with any other modules in the past.

**Comment by ichrisroberts** [comment]
Did you unblock the zip file before extracting it to the Modules folder?

**Comment by ashishdhingra** [comment]
@efie45 The installation instructions mentioned in the documentation are the basic steps and should not cause any issues. Could you please ensure that your are running PowerShell session as an Administrator elevated privileges? Also, could you also confirm the PowerShell version - is it Windows PowerShell 5.1 or PowerShell Core 7.x? Windows PowerShell 5.1 is known to have some intermittent issues due to incorrect versioned folder name, the error which gets resolves by itself subsequently.
