### ISSUE TITLE
Create temporary credentials for Region eu-west-1 with get-stssessiontoken: unauthorized

### ISSUE THREAD

**Issue by tabbedy** [aws/aws-tools-for-powershell#253]
Hi all, i Tried to generate temporary credentials with get-stssessiontoken dir Region eu-west-1. The Generation was successful, but sellingpartner API result ist unauthorized. I Tried to generate stssessiontoken with the Same AWS credentials via sts endpoint for Region eu-west-1 and Used them in my code. After this my api requests was successful.

I also Tried to Set the endpoint via die Endpointuri Parameter to HTTPS://sts.eu-west-1.amazonaws.com. the  authorization was Not successful. 

Can anybody Help, please?

**Comment by ashishdhingra** [comment]
Hi @tabbedy,

Good morning.

Could you please elaborate on what is sellingpartner API? Kindly elaborate the details in the below template:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish
