### ISSUE TITLE
AWS.Tools.* modules require all to be updated before a new module can be installed

### ISSUE THREAD

**Issue by chadish7** [aws/aws-tools-for-powershell#38]
When installing a new module with the command `Install-Module AWS.Tools.FantasticService` when the version of this new module is higher than the currently installed AWS.Tools.Common Module an error is produced stating that the version required of AWS.Tools.Common must match the version of the new module being installed and the install fails.

A workaround is to run `Update-Module AWS.Tools.*` prior to `Install-Module` but maybe the error or module handling could be better here?

**Comment by matteo-prosperi** [comment]
Hello,
we plan to improve on the error message and suggest the cmdlet that can be used to update the modules.

The requirement to have all modules at the same version is described in the "Versioning" section of the [announcement](https://github.com/aws/aws-tools-for-powershell/issues/33).

The requirement is necessary in order to maintain a coherent and stable behavior and it is a due to the inter-dependencies between modules and between AWS SDK for .NET libraries distributed inside the modules..
