### ISSUE TITLE
AWS.Tools.SimpleSystemsManager Module uses legacy name

### ISSUE THREAD

**Issue by chadish7** [aws/aws-tools-for-powershell#39]
The name of this module should either be AWS.Tools.SSM or AWS.Tools.SystemsManager to align with current CLI commands or the current service name respectively. The name it is using is the legacy name of the service.

**Comment by adcreech** [comment]
Just to add to this, details of the service's naming history can be found [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-systems-manager.html#service-naming-history). The additional side effect is the Powershell reference for the service is now found under the legacy name [SimpleSystemsManagement](https://docs.aws.amazon.com/powershell/latest/reference/index.html?page=SimpleSystemsManagement_cmdlets.html&tocid=SimpleSystemsManagement_cmdlets) based on the module name.

**Comment by matteo-prosperi** [comment]
@chadish7 @adcreech Thanks for your question,
AWS.Tools use service abbreviations that are shared with the [AWS SDK for .NET](https://github.com/aws/aws-sdk-net).

This is done in order to have coherent names across .NET namespace (Amazon.SimpleSystemsManagement), service client ([AmazonSimpleSystemsManagementClient](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleSystemsManagement/Generated/_mobile/AmazonSimpleSystemsManagementClient.cs)), library ([AWSSDK.SimpleSystemsManagement](https://www.nuget.org/packages/AWSSDK.SimpleSystemsManagement/)) and PowerShell module.

It is important to keep coherency between these names because PowerShell users mix and match usage of both cmdlets and AWS SDK for .NET classes.

At AWS we consider backward compatibility very seriously, for this reason, name deprecation can take a very long time.
