### ISSUE TITLE
Improve install, uninstall, update experience. Improve discoverability of modules and cmdlets.

### ISSUE THREAD

**Issue by yobyot** [aws/aws-tools-for-powershell#42]
Breaking up the monolithic cmdlet modules has some negative impacts on usability.

First, there's the problem of synching .Common with everything else, as described in #38. 

Beyond that, there are additional issues I hope you can address over time.

- It would still be nice, like Azure does with Az, to `Install-Module [some includes-all-modules-name` to install all the modules. Many DevOps like me don't care about having all the modules available -- I don't know what I am going to want when. I also work on multiple machines and keeping track of which module is installed where is complicated when they are in little(r) pieces.
- PowerShell Gallery is a hot mess. I couldn't find any of the new module there from a search, so relying on people finding them in the web UI, which brings up my biggest issue:
- Where are the names of every cmdlet-let going to be documented? How do I find the right name for the module I want in the absence of a super-packaging that installs everything?

While I appreciate that the `AWSPowerShell.NetCore` had grown too large for you, decomposing it makes additional work for some users like me who had grown used to getting everything at once. In my world, waiting five seconds for the fat boy to load into memory is worth the wait because it was convenient.

AWS.Tools.* may be svelte but skinny ain't everything. :-)

**Comment by matteo-prosperi** [comment]
Hello,
thanks for reaching out. Now that we are shaping the new modular AWS Tools for PowerShell we are even more interested in user feedback.

- We are currently considering the creation of a utility module to handle install, uninstall and update of all (or the currently installed) AWS.Tools.* modules. We realize that especially the uninstall experience is painful.
- We considered the option of a catch-all module that would have all others as dependency in order to allow global install, import and update of all AWS.Tools modules. Unfortunately PowerShell, especially older versions, is really slow to import many small modules. So we have decided not to publish a module that would import hundreds of others taking minutes to do so.
- You can find the list of all cmdlets [here](https://docs.aws.amazon.com/powershell/latest/reference/Index.html). You can also use `Get-AWSCmdletName` to get the list of all cmdlets from imported AWS.Tools modules (we are planning to extend this to include cmdlets from AWS.Tools modules that are not imported or installed). You can also use `Get-Command -Module AWS.Tools.*` for a list of all cmdlets from installed modules.
- The docs pages [here](https://docs.aws.amazon.com/powershell/latest/reference/Index.html] also contain a list of all modules and their link to the gallery. We will also add an easier to navigate list to this repo.
- At least for the foreseeable future AWSPowerShell and AWSPowerShell.NetCore are not going away, so feel free to continue using those if they better fir your use case. We completely understand that there are cases when you may want everything and getting it in a single module is simpler.
- Indeed AWSPowerShell is too big, not only for our personal taste but for also for what is supported by Microsoft at this time. I think we are currently exporting three times as many cmdlet as it is allowed by the module manifest. :-)

Thanks again for the feedback!

**Comment by matteo-prosperi** [comment]
Hello,
thanks for opening this issue.
We have created the [AWS.Tools.Installer](https://www.powershellgallery.com/packages/AWS.Tools.Installer) module to simplify installation, uninstallation and update of the AWS.Tools.Module.

The next release of AWS.Tool will also include a Get-AWSService cmdlet allowing to list the available modules.

**Comment by matteo-prosperi** [comment]
Get-AWSService is now available in AWS Tools for PowerShell version 4. AWS.Tools.Installer is also available for use in production environments.
